

trigger:
  branches:
        include:
            - master
  paths:
        include:
            - azure-pipelines.yml
            - StoreApplication



 

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: dotnet 5.0
  inputs:
    packageType: 'sdk'
    version: '5.0.x'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
  workingDirectory: StoreApplication

- task: DotNetCoreCLI@2
  displayName: dotnet test
  inputs:
    command: 'test'
    workingDirectory: StoreApplication
    publishTestResults: true