

trigger:
  branches:
        include:
            - master
  paths:
        include:
            - StoreApplication



 

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '5.0.x'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
  workingDirectory: StoreApplication
# ASP.NET Core
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(2f48b30f-7fe3-404e-90b7-a9e6dfbbda20)'
    appType: 'webApp'
    WebAppName: 'Hao-Techland2'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
