

trigger:
  branches:
        include:
            - master
  paths:
        include:
            - azure-pipelines.yml
            - StoreApplication
pr: none
stages:
- stage: build 
  jobs:
  - job: build
    pool:
      vmImage: 'ubuntu-latest'

    variables:
      buildConfiguration: 'Release'

    steps:
    - task: UseDotNet@2
      displayName: dotnet 2.0
      inputs:
        packageType: 'sdk'
        version: '2.x'
    - task: SonarCloudPrepare@1
      displayName: sonar prep
      inputs:
        SonarCloud: 'SonarClound-Proj1'
        organization: '2011-nov02-net'
        scannerMode: 'MSBuild'
        projectKey: '2011-nov02-net_hao-project1'
        projectName: 'Techland 2.0 Sonar'
        extraProperties: 'sonar.exclusions=**/lib/**'

    - task: UseDotNet@2
      displayName: dotnet 5.0
      inputs:
        packageType: 'sdk'
        version: '5.0.x'

    - script: dotnet build --configuration $(buildConfiguration)
      displayName: 'dotnet build $(buildConfiguration)'
      workingDirectory: StoreApplication

    - task: SonarCloudAnalyze@1
      displayName: sonar run analysis
    - task: SonarCloudPublish@1
      displayName: sonar analysis publish
      inputs:
        pollingTimeoutSec: '300'


    - task: DotNetCoreCLI@2
      displayName: dotnet test
      inputs:
        command: 'test'
        workingDirectory: StoreApplication
        publishTestResults: true

    - script: dotnet publish --configuration $(buildConfiguration) --output publish
      displayName: dotnet publish
      workingDirectory: StoreApplication
##- task: AzureRmWebAppDeployment@4
  ##condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  ##inputs:
    ##ConnectionType: 'AzureRM'
    ##azureSubscription: 'Azure subscription 1(2f48b30f-7fe3-404e-90b7-a9e6dfbbda20)'
    ##appType: 'webApp'
    ##WebAppName: 'Hao-Techland2'
    ##packageForLinux: 'StoreApplication/publish'